-- 027_ai_rescore.sql
-- Sprint G / Commit 2: AI re-score + sales snippet + cron observability.
--
-- Note: spec said "Migration 026" but 026 уже used by matching_engine.
-- Renumber до 027.
--
-- Adds:
--   - matches.ai_score / ai_reasoning / ai_confidence / ai_scored_at
--     (populated by L6 Claude Haiku re-score on TOP-20 per product)
--   - matches.sales_snippet JSONB (on-demand cold-opener / value-prop)
--   - matches.combined_score INT GENERATED — coalesces ai_score → algo_score
--   - cron_runs table — observability dla matching-refresh / hygiene-scan
--
-- Idempotent.

-- ─────── matches AI columns ───────
ALTER TABLE matches ADD COLUMN IF NOT EXISTS ai_score INT
  CHECK (ai_score IS NULL OR (ai_score >= 0 AND ai_score <= 100));
ALTER TABLE matches ADD COLUMN IF NOT EXISTS ai_reasoning TEXT;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS ai_confidence NUMERIC(3,2)
  CHECK (ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1));
ALTER TABLE matches ADD COLUMN IF NOT EXISTS ai_scored_at TIMESTAMPTZ;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS sales_snippet JSONB;

-- combined_score: ai_score wins коли non-null, else algo_score.
-- GENERATED STORED для index efficiency на /matches/global default sort.
ALTER TABLE matches DROP COLUMN IF EXISTS combined_score;
ALTER TABLE matches ADD COLUMN combined_score INT
  GENERATED ALWAYS AS (
    CASE WHEN ai_score IS NOT NULL THEN ai_score ELSE algo_score END
  ) STORED;

CREATE INDEX IF NOT EXISTS idx_matches_combined_score
  ON matches(combined_score DESC) WHERE combined_score >= 50;

CREATE INDEX IF NOT EXISTS idx_matches_ai_scored_at
  ON matches(ai_scored_at DESC) WHERE ai_scored_at IS NOT NULL;

COMMENT ON COLUMN matches.ai_score IS
  'L6 AI re-score by Claude Haiku 4.5. NULL = not yet evaluated. Range 0-100.
   Populated on-demand for TOP-20 candidates per product (rescoreTop20).';
COMMENT ON COLUMN matches.combined_score IS
  'AI-or-algo coalesced score. Used as default sort у /matches/global.';
COMMENT ON COLUMN matches.sales_snippet IS
  'On-demand cold-opener+value-prop+objection JSON, cached. Generated by
   POST /api/matches/{id}/generate-snippet. NULL = not yet generated.';

-- ─────── cron_runs (observability) ───────
CREATE TABLE IF NOT EXISTS cron_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_name TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'error')),
  pairs_processed INTEGER,
  duration_ms INTEGER,
  error_message TEXT,
  meta JSONB
);

CREATE INDEX IF NOT EXISTS cron_runs_job_started_idx
  ON cron_runs(job_name, started_at DESC);
CREATE INDEX IF NOT EXISTS cron_runs_started_idx
  ON cron_runs(started_at DESC);

ALTER TABLE cron_runs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "cron_runs_authenticated_all" ON cron_runs
    FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMENT ON TABLE cron_runs IS
  'Telemetry per cron job invocation. INSERT row at start (status=running),
   UPDATE on finish (success/error + pairs/duration). Powers /admin/health
   widget — last 5 runs per job, red signal якщо stale > 8 days або status=error.';
