-- 057_products_business_profile.sql
-- Sprint S-CORE.3.A α' — products.business_profile JSONB + last_analyzed_at.
--
-- Mirror migration 033 (clients.business_profile) but для products table.
-- Stores Claude Sonnet output для "Analiza produktu" CTA on /produkty
-- detail panel: sales strategy per segment (hot/warm/cold), pitch, next
-- steps. Triggered через /api/products/[id]/full-analysis.
--
-- Shape (typed inline у ProductBusinessProfile interface client-side):
--   { segments: { hot, warm, cold }
--     pitch_per_segment: { hot, warm, cold }
--     next_steps: string[]
--     analyzed_at, model_used, cost_usd
--     input_context: { product_name, sku, price_pln, category,
--                      total_clients, top_matches } }
--
-- Idempotent.

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS business_profile JSONB,
  ADD COLUMN IF NOT EXISTS last_analyzed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_products_business_profile_gin
  ON products USING gin(business_profile);

-- Extend enrichment_log target_type CHECK to allow 'product'.
-- Existing constraint per migration 031: ('company', 'person').
-- DROP + recreate is safe (idempotent — no data violates new
-- superset constraint).
ALTER TABLE enrichment_log
  DROP CONSTRAINT IF EXISTS enrichment_log_target_type_check;
ALTER TABLE enrichment_log
  ADD CONSTRAINT enrichment_log_target_type_check
  CHECK (target_type IN ('company', 'person', 'product'));

COMMENT ON COLUMN products.business_profile IS
  'AI-generated sales strategy (Claude Sonnet 4.6). Shape:
   {segments: {hot, warm, cold}, pitch_per_segment: {hot, warm, cold},
    next_steps[], analyzed_at, model_used, cost_usd, input_context}.
   Generated by /api/products/[id]/full-analysis (Phase S-CORE.3.A α'').';

COMMENT ON COLUMN products.last_analyzed_at IS
  'Timestamp останнього "Analiza produktu" run. Used для UI hint про
   recency у produkty detail panel.';
