// scripts/setup-env.ts
// Auto-generate .env.local from secrets stored in Supabase Management
// API + params table. Idempotent: overwrite each run (tokens rotate).
//
// Bootstrap (one-time): SUPABASE_ACCESS_TOKEN must be available via:
//   1. Existing .env.local with `SUPABASE_ACCESS_TOKEN=sbp_...`
//   2. process.env.SUPABASE_ACCESS_TOKEN
//   3. Supabase CLI auth file (~/.supabase/access-token)
//
// After bootstrap, all rotations refresh via single `pnpm dlx tsx
// scripts/setup-env.ts` re-run.

import 'dotenv/config'

import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'

const PROJECT_REF = 'pxovjyxsktxdbovmybxz'
const SUPABASE_URL = `https://${PROJECT_REF}.supabase.co`
const MGMT_API_BASE = 'https://api.supabase.com/v1'
const ENV_LOCAL_PATH = path.resolve(process.cwd(), '.env.local')

// ────────────────────────────────────────────────────────────
// Bootstrap: find SUPABASE_ACCESS_TOKEN from any of 3 sources
// ────────────────────────────────────────────────────────────

async function findAccessToken(): Promise<string> {
  // 1. process.env (loaded by dotenv/config from .env.local OR set externally)
  if (process.env.SUPABASE_ACCESS_TOKEN?.startsWith('sbp_')) {
    console.log('  ✓ Using SUPABASE_ACCESS_TOKEN from env (.env.local or shell)')
    return process.env.SUPABASE_ACCESS_TOKEN
  }

  // 2. Supabase CLI auth file (cross-platform)
  const cliTokenPath = path.join(os.homedir(), '.supabase', 'access-token')
  try {
    const cliToken = (await fs.readFile(cliTokenPath, 'utf-8')).trim()
    if (cliToken.startsWith('sbp_')) {
      console.log(`  ✓ Using access token via Supabase CLI (${cliTokenPath})`)
      return cliToken
    }
  } catch {
    // file doesn't exist — fine
  }

  throw new Error(
    [
      'No SUPABASE_ACCESS_TOKEN found. Bootstrap options:',
      '',
      '  (a) Create .env.local in project root з one line:',
      '      SUPABASE_ACCESS_TOKEN=sbp_...',
      '      (Get from Dashboard → Account → Access Tokens)',
      '',
      '  (b) Install Supabase CLI and run `supabase login`',
      '      (writes ~/.supabase/access-token)',
    ].join('\n'),
  )
}

// ────────────────────────────────────────────────────────────
// Management API helpers
// ────────────────────────────────────────────────────────────

async function fetchProjectApiKeys(accessToken: string): Promise<{
  anonKey: string
  serviceRoleKey: string
}> {
  const url = `${MGMT_API_BASE}/projects/${PROJECT_REF}/api-keys?reveal=true`
  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${accessToken}` },
    signal: AbortSignal.timeout(20_000),
  })
  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new Error(`api-keys fetch failed (${response.status}): ${body.slice(0, 300)}`)
  }
  const keys = (await response.json()) as Array<{
    name?: string
    api_key?: string
    [k: string]: unknown
  }>
  if (!Array.isArray(keys)) {
    throw new Error(`Unexpected api-keys shape: ${JSON.stringify(keys).slice(0, 300)}`)
  }
  const anonKey = keys.find((k) => k.name === 'anon')?.api_key
  const serviceRoleKey = keys.find((k) => k.name === 'service_role')?.api_key
  if (!anonKey || !serviceRoleKey) {
    throw new Error(
      `Missing anon or service_role in response. Got names: ${keys.map((k) => k.name).join(', ')}`,
    )
  }
  return { anonKey, serviceRoleKey }
}

async function fetchParamsSecrets(
  accessToken: string,
): Promise<Record<string, string | null>> {
  const sql = `SELECT
    anthropic_api_key,
    ceidg_api_key,
    apify_api_token,
    krs_rejestr_api_token,
    gemini_key,
    supabase_access_token
  FROM params
  LIMIT 1`

  const url = `${MGMT_API_BASE}/projects/${PROJECT_REF}/database/query`
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query: sql }),
    signal: AbortSignal.timeout(20_000),
  })

  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new Error(`params query failed (${response.status}): ${body.slice(0, 300)}`)
  }

  const rows = (await response.json()) as Array<Record<string, string | null>>
  if (!Array.isArray(rows) || rows.length === 0) {
    throw new Error('params table is empty or query returned no rows')
  }
  return rows[0]
}

// ────────────────────────────────────────────────────────────
// .env.local writer
// ────────────────────────────────────────────────────────────

function buildEnvFile(values: Record<string, string | null | undefined>): string {
  const lines = [
    '# .env.local — auto-generated by scripts/setup-env.ts',
    `# Generated: ${new Date().toISOString()}`,
    '# DO NOT COMMIT (covered by .gitignore .env*.local pattern)',
    '# Re-run `pnpm dlx tsx scripts/setup-env.ts` to refresh after rotation',
    '',
  ]
  const sortedKeys = Object.keys(values).sort()
  for (const key of sortedKeys) {
    const value = values[key]
    if (value !== undefined && value !== null && value !== '') {
      lines.push(`${key}=${value}`)
    }
  }
  return lines.join('\n') + '\n'
}

// ────────────────────────────────────────────────────────────
// Main
// ────────────────────────────────────────────────────────────

async function main() {
  console.log('\n══════ setup-env.ts ══════\n')

  console.log('[1/3] Locating bootstrap access token...')
  const accessToken = await findAccessToken()

  console.log('\n[2/3] Fetching API keys via Management API /api-keys...')
  const { anonKey, serviceRoleKey } = await fetchProjectApiKeys(accessToken)
  console.log(`  ✓ anon (len=${anonKey.length})`)
  console.log(`  ✓ service_role (len=${serviceRoleKey.length})`)

  console.log('\n[3/3] Fetching secrets from params table...')
  const params = await fetchParamsSecrets(accessToken)
  for (const [k, v] of Object.entries(params)) {
    const status = v ? `✓ (len=${v.length})` : '— (empty)'
    console.log(`  ${status.startsWith('✓') ? '✓' : '—'} params.${k} ${status.startsWith('✓') ? `(len=${v?.length})` : '(empty)'}`)
  }

  // Use newer access token from params if it exists (e.g. after rotation)
  const finalAccessToken = params.supabase_access_token ?? accessToken

  const envContent = buildEnvFile({
    NEXT_PUBLIC_SUPABASE_URL: SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: anonKey,
    SUPABASE_SERVICE_ROLE_KEY: serviceRoleKey,
    SUPABASE_ACCESS_TOKEN: finalAccessToken,
    ANTHROPIC_API_KEY: params.anthropic_api_key,
    CEIDG_API_KEY: params.ceidg_api_key,
    APIFY_API_TOKEN: params.apify_api_token,
    KRS_REJESTR_API_TOKEN: params.krs_rejestr_api_token,
    GEMINI_API_KEY: params.gemini_key, // legacy, kept for backward compat
  })

  await fs.writeFile(ENV_LOCAL_PATH, envContent, { mode: 0o600 })
  console.log(`\n✅ Wrote ${ENV_LOCAL_PATH}`)
  console.log(`   ${envContent.length} bytes, mode 600`)
  console.log(`\nAll Node scripts that import 'dotenv/config' will now read these automatically.`)
}

main().catch((err) => {
  console.error('\n❌ setup-env.ts failed:', err instanceof Error ? err.message : err)
  process.exit(1)
})
